SET XACT_ABORT ON;

BEGIN TRANSACTION;

ALTER TABLE tickets
    ALTER COLUMN causaraiz VARCHAR(2000) NULL;

ALTER TABLE tickets
    ALTER COLUMN solucionpropuesta VARCHAR(2000) NULL;

COMMIT TRANSACTION;
